apiVersion: v1
kind: Service
metadata:
  name: zwave-js-ui
  labels:
    app: zwave-js-ui
spec:
  selector:
    app: zwave-js-ui
  ports:
    - name: ws
      port: 3000
      targetPort: ws
    - name: ui
      port: 8091
      targetPort: ui
